// Multi-tenant database simulation using localStorage for Mercado Online Facilitadora

const INITIAL_COMPANIES = {
  "coqueiro": {
    id: "coqueiro",
    name: "Casa Coqueiro",
    tradeName: "Casa Coqueiro Supermercados",
    logoUrl: "https://casacoqueiro.com.br/wp-content/uploads/2023/11/dddd-1.png",
    logoType: "image",
    primaryColor: "#059669", // Green
    secondaryColor: "#eab308", // Yellow
    accentColor: "#ef4444", // Red
    address: "Av. Copacabana, 500 - Copacabana, Rio de Janeiro - RJ",
    phone: "(21) 2233-4455",
    whatsapp: "(21) 98888-9999",
    hours: "08:00 às 20:00"
  },
  "horti-verde": {
    id: "horti-verde",
    name: "Hortifruti Verde Vale",
    tradeName: "Verde Vale Hortifruti & Cia",
    logoUrl: "",
    logoType: "text",
    logoText: "VerdeVale",
    primaryColor: "#16a34a",
    secondaryColor: "#166534",
    accentColor: "#ea580c",
    address: "Rua das Laranjeiras, 120 - Laranjeiras, Rio de Janeiro - RJ",
    phone: "(21) 3344-5566",
    whatsapp: "(21) 97777-8888",
    hours: "07:00 às 19:00"
  },
  "clubbi": {
    id: "clubbi",
    name: "Clubbi",
    tradeName: "Clubbi Distribuição B2B",
    logoUrl: "",
    logoType: "text",
    logoText: "Clubbi",
    primaryColor: "#3e34d3",
    secondaryColor: "#ece6fc",
    accentColor: "#38c172",
    address: "Av. das Américas, 500 - Barra da Tijuca, Rio de Janeiro - RJ",
    phone: "(21) 3003-4455",
    whatsapp: "(21) 96442-2488",
    hours: "08:00 às 18:00"
  }
};

const INITIAL_USERS = {
  // Global Admin Master
  "MASTER": {
    code: "MASTER",
    name: "Admin Master",
    role: "admin-master", // admin-master, store-admin, gestor, vendedor, cliente
    status: "Active",
    companyId: null
  },
  // Master Admin (WDPHP)
  "WDPHP": {
    code: "WDPHP",
    name: "Thiago (Admin Master)",
    role: "admin-master",
    status: "Active",
    companyId: null,
    phone: "21964422488"
  },
  // Client Test for Clubbi
  "CLI-CLUBBI": {
    code: "CLI-CLUBBI",
    name: "Mercadinho Bogados (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "clubbi",
    phone: "21964422488",
    address: "R. Cap. Edmundo Soares, 18 - K11 - Caonze, Nova Iguaçu - RJ, 26250-240"
  },
  // Store Admin - Casa Coqueiro
  "ADM01": {
    code: "ADM01",
    name: "Roberto Coqueiro (Admin)",
    role: "store-admin",
    status: "Active",
    companyId: "coqueiro"
  },
  // Gestor - Casa Coqueiro
  "GES01": {
    code: "GES01",
    name: "Fernanda Lima (Gestor)",
    role: "gestor",
    status: "Active",
    companyId: "coqueiro",
    // Toggle-based permission states
    permissions: {
      financeiro: true,
      produtos: true,
      precos: true,
      clientes: true,
      funcionarios: true,
      relatorios: true,
      impressao: true,
      visualConfig: true,
      estoque: true,
      usuarios: true
    }
  },
  // Vendedor - Casa Coqueiro
  "VEN01": {
    code: "VEN01",
    name: "Carlos Silva (Vendedor)",
    role: "vendedor",
    status: "Active",
    companyId: "coqueiro",
    permissions: {
      financeiro: false,
      produtos: false,
      precos: false,
      clientes: true,
      funcionarios: false,
      relatorios: false,
      impressao: true,
      visualConfig: false,
      estoque: false,
      usuarios: false
    }
  },
  // Clients
  "CLI01": {
    code: "CLI01",
    name: "Restaurante Tempero Bom (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "coqueiro",
    phone: "(21) 98765-4321"
  },
  "CLI02": {
    code: "CLI02",
    name: "Padaria Copacabana (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "coqueiro",
    phone: "(21) 95555-4444"
  },
  "CLI03": {
    code: "CLI03",
    name: "Lanchonete Verde Vale (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "horti-verde",
    phone: "(21) 91111-2222"
  }
};

const INITIAL_PRODUCTS = [
  // Casa Coqueiro Catalog
  {
    id: "coq-1",
    code: "COQ-101",
    description: "Biscoito Recheado Chocolate Piraquê Pacote 160g",
    category: "Mercearia",
    brand: "Piraquê",
    unit: "Un",
    price: 2.96,
    stock: 150,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760357",
    companyId: "coqueiro"
  },
  {
    id: "coq-2",
    code: "COQ-102",
    description: "Isotônico Gatorade Pet Laranja 500ml",
    category: "Bebidas",
    brand: "Gatorade",
    unit: "Un",
    price: 4.85,
    stock: 80,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7892840808020",
    companyId: "coqueiro"
  },
  {
    id: "coq-3",
    code: "COQ-103",
    description: "Banana Prata de Hortifruti Clássica Kg",
    category: "Hortifruti",
    brand: "Produtor Rio",
    unit: "Kg",
    price: 6.90,
    stock: 200,
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=200&auto=format&fit=crop&q=80",
    companyId: "coqueiro"
  },
  {
    id: "coq-4",
    code: "COQ-104",
    description: "Cereal Matinal Sucrilhos Kellogg's Original 110g",
    category: "Mercearia",
    brand: "Kellogg's",
    unit: "Un",
    price: 4.23,
    stock: 120,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896004007632",
    companyId: "coqueiro"
  },
  {
    id: "coq-5",
    code: "COQ-105",
    description: "Macarrão Instantâneo Galinha Nissin Miojo 85g",
    category: "Mercearia",
    brand: "Nissin",
    unit: "Un",
    price: 2.24,
    stock: 300,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7891079000229",
    companyId: "coqueiro"
  },
  {
    id: "coq-6",
    code: "COQ-106",
    description: "Leite de Coco Menina Garrafa 200ml",
    category: "Mercearia",
    brand: "Menina",
    unit: "Un",
    price: 3.10,
    stock: 90,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896028014494",
    companyId: "coqueiro"
  },

  // Hortifruti Verde Vale Catalog
  {
    id: "hv-1",
    code: "HVV-201",
    description: "Alface Crespa Hidropônica Unidade",
    category: "Hortifruti",
    brand: "Verde Vale",
    unit: "Un",
    price: 3.50,
    stock: 60,
    imageUrl: "https://images.unsplash.com/photo-1622484211148-716598e04141?w=200&auto=format&fit=crop&q=80",
    companyId: "horti-verde"
  },
  {
    id: "hv-2",
    code: "HVV-202",
    description: "Tomate Italiano maduro Selecionado Kg",
    category: "Hortifruti",
    brand: "Fazenda Orgânica",
    unit: "Kg",
    price: 8.90,
    stock: 140,
    imageUrl: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=200&auto=format&fit=crop&q=80",
    companyId: "horti-verde"
  },
  {
    id: "hv-3",
    code: "HVV-203",
    description: "Suco de Uva Integral Aliança 1L",
    category: "Bebidas",
    brand: "Aliança",
    unit: "Un",
    price: 14.90,
    stock: 50,
    imageUrl: "",
    companyId: "horti-verde"
  },
  {
    id: "clubbi-9171",
    code: "CLB-100",
    description: "Biscoito Recheado Chocolate Piraquê Pacote 160g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760357",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 85.5
  },
  {
    id: "clubbi-3742",
    code: "CLB-101",
    description: "Biscoito Recheado Limão Piraquê Pacote 160g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760371",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 85.5
  },
  {
    id: "clubbi-9172",
    code: "CLB-102",
    description: "Biscoito Recheado Morango Piraquê Pacote 160g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760364",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 85.5
  },
  {
    id: "clubbi-97694",
    code: "CLB-103",
    description: "Biscoito Maizena Piraquê Pacote 175g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 48",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024761651",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 136.8
  },
  {
    id: "clubbi-99429",
    code: "CLB-104",
    description: "Biscoito Leite Maltado Original Piraquê Pacote 132g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 50",
    price: 2.8,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024761439",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 134.5
  },
  {
    id: "clubbi-6144",
    code: "CLB-105",
    description: "Creme De Leite Leve Italac Tetra Pack 200g",
    category: "Derivados de Leite",
    brand: "Italac",
    unit: "Cx c/ 24",
    price: 2.65,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7898080640222",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 61.2
  },
  {
    id: "clubbi-3778",
    code: "CLB-106",
    description: "Leite De Coco Menina 200ml",
    category: "Preparo de Sobremesas",
    brand: "Menina",
    unit: "Cx c/ 24",
    price: 2.24,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896028014494",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 51.6
  },
  {
    id: "clubbi-1398",
    code: "CLB-107",
    description: "Macarrão Instantâneo Galinha Caipira Nissin Miojo Lámen Pacote 85g",
    category: "Massas Secas",
    brand: "Nissin",
    unit: "Cx c/ 50",
    price: 2.24,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7891079000229",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 107.5
  }
,
  {
    id: "clubbi-mock-1",
    code: "CLB-MOCK-1",
    description: "Produto de Teste 1 Mondelez Frios",
    category: "Frios",
    brand: "Mondelez",
    unit: "Cx c/ 12",
    price: 44.00,
    stock: 204,
    imageUrl: "https://placehold.co/300x300?text=Produto+1",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 501.60
  },
  {
    id: "clubbi-mock-2",
    code: "CLB-MOCK-2",
    description: "Produto de Teste 2 Yoki Higiene",
    category: "Higiene",
    brand: "Yoki",
    unit: "Cx c/ 30",
    price: 15.61,
    stock: 248,
    imageUrl: "https://placehold.co/300x300?text=Produto+2",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 444.88
  },
  {
    id: "clubbi-mock-3",
    code: "CLB-MOCK-3",
    description: "Produto de Teste 3 Coca-Cola Limpeza",
    category: "Limpeza",
    brand: "Coca-Cola",
    unit: "Cx c/ 24",
    price: 39.46,
    stock: 103,
    imageUrl: "https://placehold.co/300x300?text=Produto+3",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 899.69
  },
  {
    id: "clubbi-mock-4",
    code: "CLB-MOCK-4",
    description: "Produto de Teste 4 Danone Biscoitos",
    category: "Biscoitos",
    brand: "Danone",
    unit: "Cx c/ 50",
    price: 44.27,
    stock: 190,
    imageUrl: "https://placehold.co/300x300?text=Produto+4",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2102.82
  },
  {
    id: "clubbi-mock-5",
    code: "CLB-MOCK-5",
    description: "Produto de Teste 5 Pepsico Biscoitos",
    category: "Biscoitos",
    brand: "Pepsico",
    unit: "Cx c/ 30",
    price: 33.04,
    stock: 239,
    imageUrl: "https://placehold.co/300x300?text=Produto+5",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 941.64
  },
  {
    id: "clubbi-mock-6",
    code: "CLB-MOCK-6",
    description: "Produto de Teste 6 Coca-Cola Higiene",
    category: "Higiene",
    brand: "Coca-Cola",
    unit: "Cx c/ 12",
    price: 47.02,
    stock: 72,
    imageUrl: "https://placehold.co/300x300?text=Produto+6",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 536.03
  },
  {
    id: "clubbi-mock-7",
    code: "CLB-MOCK-7",
    description: "Produto de Teste 7 Nestlé Biscoitos",
    category: "Biscoitos",
    brand: "Nestlé",
    unit: "Cx c/ 48",
    price: 25.73,
    stock: 248,
    imageUrl: "https://placehold.co/300x300?text=Produto+7",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 1173.29
  },
  {
    id: "clubbi-mock-8",
    code: "CLB-MOCK-8",
    description: "Produto de Teste 8 Mondelez Limpeza",
    category: "Limpeza",
    brand: "Mondelez",
    unit: "Cx c/ 30",
    price: 34.84,
    stock: 141,
    imageUrl: "https://placehold.co/300x300?text=Produto+8",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 992.94
  },
  {
    id: "clubbi-mock-9",
    code: "CLB-MOCK-9",
    description: "Produto de Teste 9 Unilever Biscoitos",
    category: "Biscoitos",
    brand: "Unilever",
    unit: "Cx c/ 50",
    price: 33.20,
    stock: 143,
    imageUrl: "https://placehold.co/300x300?text=Produto+9",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1577.00
  },
  {
    id: "clubbi-mock-10",
    code: "CLB-MOCK-10",
    description: "Produto de Teste 10 BRF Mercearia",
    category: "Mercearia",
    brand: "BRF",
    unit: "Cx c/ 48",
    price: 34.01,
    stock: 119,
    imageUrl: "https://placehold.co/300x300?text=Produto+10",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 1550.86
  },
  {
    id: "clubbi-mock-11",
    code: "CLB-MOCK-11",
    description: "Produto de Teste 11 Bauducco Mercearia",
    category: "Mercearia",
    brand: "Bauducco",
    unit: "Cx c/ 50",
    price: 17.75,
    stock: 121,
    imageUrl: "https://placehold.co/300x300?text=Produto+11",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 843.13
  },
  {
    id: "clubbi-mock-12",
    code: "CLB-MOCK-12",
    description: "Produto de Teste 12 Pepsico Biscoitos",
    category: "Biscoitos",
    brand: "Pepsico",
    unit: "Cx c/ 30",
    price: 36.93,
    stock: 79,
    imageUrl: "https://placehold.co/300x300?text=Produto+12",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1052.51
  },
  {
    id: "clubbi-mock-13",
    code: "CLB-MOCK-13",
    description: "Produto de Teste 13 Ambev Limpeza",
    category: "Limpeza",
    brand: "Ambev",
    unit: "Cx c/ 12",
    price: 23.27,
    stock: 197,
    imageUrl: "https://placehold.co/300x300?text=Produto+13",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 265.28
  },
  {
    id: "clubbi-mock-14",
    code: "CLB-MOCK-14",
    description: "Produto de Teste 14 Mondelez Mercearia",
    category: "Mercearia",
    brand: "Mondelez",
    unit: "Cx c/ 12",
    price: 5.50,
    stock: 93,
    imageUrl: "https://placehold.co/300x300?text=Produto+14",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 62.70
  },
  {
    id: "clubbi-mock-15",
    code: "CLB-MOCK-15",
    description: "Produto de Teste 15 Yoki Limpeza",
    category: "Limpeza",
    brand: "Yoki",
    unit: "Cx c/ 12",
    price: 49.04,
    stock: 246,
    imageUrl: "https://placehold.co/300x300?text=Produto+15",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 559.06
  },
  {
    id: "clubbi-mock-16",
    code: "CLB-MOCK-16",
    description: "Produto de Teste 16 Nestlé Biscoitos",
    category: "Biscoitos",
    brand: "Nestlé",
    unit: "Cx c/ 24",
    price: 27.33,
    stock: 134,
    imageUrl: "https://placehold.co/300x300?text=Produto+16",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 623.12
  },
  {
    id: "clubbi-mock-17",
    code: "CLB-MOCK-17",
    description: "Produto de Teste 17 Danone Limpeza",
    category: "Limpeza",
    brand: "Danone",
    unit: "Cx c/ 48",
    price: 15.02,
    stock: 211,
    imageUrl: "https://placehold.co/300x300?text=Produto+17",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 684.91
  },
  {
    id: "clubbi-mock-18",
    code: "CLB-MOCK-18",
    description: "Produto de Teste 18 Danone Higiene",
    category: "Higiene",
    brand: "Danone",
    unit: "Cx c/ 12",
    price: 43.24,
    stock: 218,
    imageUrl: "https://placehold.co/300x300?text=Produto+18",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 492.94
  },
  {
    id: "clubbi-mock-19",
    code: "CLB-MOCK-19",
    description: "Produto de Teste 19 Bauducco Frios",
    category: "Frios",
    brand: "Bauducco",
    unit: "Cx c/ 48",
    price: 43.22,
    stock: 241,
    imageUrl: "https://placehold.co/300x300?text=Produto+19",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 1970.83
  },
  {
    id: "clubbi-mock-20",
    code: "CLB-MOCK-20",
    description: "Produto de Teste 20 Unilever Mercearia",
    category: "Mercearia",
    brand: "Unilever",
    unit: "Cx c/ 24",
    price: 18.85,
    stock: 241,
    imageUrl: "https://placehold.co/300x300?text=Produto+20",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 429.78
  },
  {
    id: "clubbi-mock-21",
    code: "CLB-MOCK-21",
    description: "Produto de Teste 21 Danone Biscoitos",
    category: "Biscoitos",
    brand: "Danone",
    unit: "Cx c/ 12",
    price: 17.13,
    stock: 189,
    imageUrl: "https://placehold.co/300x300?text=Produto+21",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 195.28
  },
  {
    id: "clubbi-mock-22",
    code: "CLB-MOCK-22",
    description: "Produto de Teste 22 Ambev Bebidas",
    category: "Bebidas",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 22.90,
    stock: 154,
    imageUrl: "https://placehold.co/300x300?text=Produto+22",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 522.12
  },
  {
    id: "clubbi-mock-23",
    code: "CLB-MOCK-23",
    description: "Produto de Teste 23 BRF Bebidas",
    category: "Bebidas",
    brand: "BRF",
    unit: "Cx c/ 24",
    price: 14.42,
    stock: 220,
    imageUrl: "https://placehold.co/300x300?text=Produto+23",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 328.78
  },
  {
    id: "clubbi-mock-24",
    code: "CLB-MOCK-24",
    description: "Produto de Teste 24 Unilever Biscoitos",
    category: "Biscoitos",
    brand: "Unilever",
    unit: "Cx c/ 50",
    price: 22.59,
    stock: 184,
    imageUrl: "https://placehold.co/300x300?text=Produto+24",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1073.02
  },
  {
    id: "clubbi-mock-25",
    code: "CLB-MOCK-25",
    description: "Produto de Teste 25 Yoki Mercearia",
    category: "Mercearia",
    brand: "Yoki",
    unit: "Cx c/ 12",
    price: 33.18,
    stock: 120,
    imageUrl: "https://placehold.co/300x300?text=Produto+25",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 378.25
  },
  {
    id: "clubbi-mock-26",
    code: "CLB-MOCK-26",
    description: "Produto de Teste 26 Yoki Mercearia",
    category: "Mercearia",
    brand: "Yoki",
    unit: "Cx c/ 50",
    price: 45.82,
    stock: 149,
    imageUrl: "https://placehold.co/300x300?text=Produto+26",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2176.45
  },
  {
    id: "clubbi-mock-27",
    code: "CLB-MOCK-27",
    description: "Produto de Teste 27 Ambev Frios",
    category: "Frios",
    brand: "Ambev",
    unit: "Cx c/ 12",
    price: 45.52,
    stock: 210,
    imageUrl: "https://placehold.co/300x300?text=Produto+27",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 518.93
  },
  {
    id: "clubbi-mock-28",
    code: "CLB-MOCK-28",
    description: "Produto de Teste 28 Ambev Biscoitos",
    category: "Biscoitos",
    brand: "Ambev",
    unit: "Cx c/ 48",
    price: 51.15,
    stock: 93,
    imageUrl: "https://placehold.co/300x300?text=Produto+28",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 2332.44
  },
  {
    id: "clubbi-mock-29",
    code: "CLB-MOCK-29",
    description: "Produto de Teste 29 Danone Higiene",
    category: "Higiene",
    brand: "Danone",
    unit: "Cx c/ 24",
    price: 14.95,
    stock: 231,
    imageUrl: "https://placehold.co/300x300?text=Produto+29",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 340.86
  },
  {
    id: "clubbi-mock-30",
    code: "CLB-MOCK-30",
    description: "Produto de Teste 30 Yoki Frios",
    category: "Frios",
    brand: "Yoki",
    unit: "Cx c/ 48",
    price: 30.28,
    stock: 66,
    imageUrl: "https://placehold.co/300x300?text=Produto+30",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 1380.77
  },
  {
    id: "clubbi-mock-31",
    code: "CLB-MOCK-31",
    description: "Produto de Teste 31 Bauducco Frios",
    category: "Frios",
    brand: "Bauducco",
    unit: "Cx c/ 50",
    price: 6.10,
    stock: 67,
    imageUrl: "https://placehold.co/300x300?text=Produto+31",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 289.75
  },
  {
    id: "clubbi-mock-32",
    code: "CLB-MOCK-32",
    description: "Produto de Teste 32 Nestlé Limpeza",
    category: "Limpeza",
    brand: "Nestlé",
    unit: "Cx c/ 30",
    price: 5.67,
    stock: 147,
    imageUrl: "https://placehold.co/300x300?text=Produto+32",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 161.59
  },
  {
    id: "clubbi-mock-33",
    code: "CLB-MOCK-33",
    description: "Produto de Teste 33 Ambev Bebidas",
    category: "Bebidas",
    brand: "Ambev",
    unit: "Cx c/ 12",
    price: 43.89,
    stock: 55,
    imageUrl: "https://placehold.co/300x300?text=Produto+33",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 500.35
  },
  {
    id: "clubbi-mock-34",
    code: "CLB-MOCK-34",
    description: "Produto de Teste 34 Yoki Bebidas",
    category: "Bebidas",
    brand: "Yoki",
    unit: "Cx c/ 30",
    price: 8.02,
    stock: 149,
    imageUrl: "https://placehold.co/300x300?text=Produto+34",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 228.57
  },
  {
    id: "clubbi-mock-35",
    code: "CLB-MOCK-35",
    description: "Produto de Teste 35 BRF Bebidas",
    category: "Bebidas",
    brand: "BRF",
    unit: "Cx c/ 50",
    price: 45.86,
    stock: 245,
    imageUrl: "https://placehold.co/300x300?text=Produto+35",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2178.35
  },
  {
    id: "clubbi-mock-36",
    code: "CLB-MOCK-36",
    description: "Produto de Teste 36 Yoki Laticínios",
    category: "Laticínios",
    brand: "Yoki",
    unit: "Cx c/ 24",
    price: 35.41,
    stock: 164,
    imageUrl: "https://placehold.co/300x300?text=Produto+36",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 807.35
  },
  {
    id: "clubbi-mock-37",
    code: "CLB-MOCK-37",
    description: "Produto de Teste 37 Danone Frios",
    category: "Frios",
    brand: "Danone",
    unit: "Cx c/ 48",
    price: 2.72,
    stock: 94,
    imageUrl: "https://placehold.co/300x300?text=Produto+37",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 124.03
  },
  {
    id: "clubbi-mock-38",
    code: "CLB-MOCK-38",
    description: "Produto de Teste 38 Unilever Limpeza",
    category: "Limpeza",
    brand: "Unilever",
    unit: "Cx c/ 30",
    price: 21.13,
    stock: 122,
    imageUrl: "https://placehold.co/300x300?text=Produto+38",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 602.20
  },
  {
    id: "clubbi-mock-39",
    code: "CLB-MOCK-39",
    description: "Produto de Teste 39 Nestlé Frios",
    category: "Frios",
    brand: "Nestlé",
    unit: "Cx c/ 50",
    price: 8.46,
    stock: 217,
    imageUrl: "https://placehold.co/300x300?text=Produto+39",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 401.85
  },
  {
    id: "clubbi-mock-40",
    code: "CLB-MOCK-40",
    description: "Produto de Teste 40 Unilever Laticínios",
    category: "Laticínios",
    brand: "Unilever",
    unit: "Cx c/ 30",
    price: 17.65,
    stock: 139,
    imageUrl: "https://placehold.co/300x300?text=Produto+40",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 503.02
  },
  {
    id: "clubbi-mock-41",
    code: "CLB-MOCK-41",
    description: "Produto de Teste 41 Unilever Frios",
    category: "Frios",
    brand: "Unilever",
    unit: "Cx c/ 48",
    price: 9.21,
    stock: 213,
    imageUrl: "https://placehold.co/300x300?text=Produto+41",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 419.98
  },
  {
    id: "clubbi-mock-42",
    code: "CLB-MOCK-42",
    description: "Produto de Teste 42 Mondelez Frios",
    category: "Frios",
    brand: "Mondelez",
    unit: "Cx c/ 30",
    price: 43.37,
    stock: 98,
    imageUrl: "https://placehold.co/300x300?text=Produto+42",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1236.04
  },
  {
    id: "clubbi-mock-43",
    code: "CLB-MOCK-43",
    description: "Produto de Teste 43 Bauducco Mercearia",
    category: "Mercearia",
    brand: "Bauducco",
    unit: "Cx c/ 24",
    price: 6.56,
    stock: 159,
    imageUrl: "https://placehold.co/300x300?text=Produto+43",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 149.57
  },
  {
    id: "clubbi-mock-44",
    code: "CLB-MOCK-44",
    description: "Produto de Teste 44 Bauducco Bebidas",
    category: "Bebidas",
    brand: "Bauducco",
    unit: "Cx c/ 12",
    price: 4.51,
    stock: 166,
    imageUrl: "https://placehold.co/300x300?text=Produto+44",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 51.41
  },
  {
    id: "clubbi-mock-45",
    code: "CLB-MOCK-45",
    description: "Produto de Teste 45 Mondelez Bebidas",
    category: "Bebidas",
    brand: "Mondelez",
    unit: "Cx c/ 50",
    price: 24.02,
    stock: 158,
    imageUrl: "https://placehold.co/300x300?text=Produto+45",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1140.95
  },
  {
    id: "clubbi-mock-46",
    code: "CLB-MOCK-46",
    description: "Produto de Teste 46 Yoki Mercearia",
    category: "Mercearia",
    brand: "Yoki",
    unit: "Cx c/ 48",
    price: 31.07,
    stock: 90,
    imageUrl: "https://placehold.co/300x300?text=Produto+46",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 1416.79
  },
  {
    id: "clubbi-mock-47",
    code: "CLB-MOCK-47",
    description: "Produto de Teste 47 Bauducco Biscoitos",
    category: "Biscoitos",
    brand: "Bauducco",
    unit: "Cx c/ 24",
    price: 22.92,
    stock: 132,
    imageUrl: "https://placehold.co/300x300?text=Produto+47",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 522.58
  },
  {
    id: "clubbi-mock-48",
    code: "CLB-MOCK-48",
    description: "Produto de Teste 48 Pepsico Laticínios",
    category: "Laticínios",
    brand: "Pepsico",
    unit: "Cx c/ 48",
    price: 12.50,
    stock: 231,
    imageUrl: "https://placehold.co/300x300?text=Produto+48",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 570.00
  },
  {
    id: "clubbi-mock-49",
    code: "CLB-MOCK-49",
    description: "Produto de Teste 49 Mondelez Laticínios",
    category: "Laticínios",
    brand: "Mondelez",
    unit: "Cx c/ 24",
    price: 8.36,
    stock: 70,
    imageUrl: "https://placehold.co/300x300?text=Produto+49",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 190.61
  },
  {
    id: "clubbi-mock-50",
    code: "CLB-MOCK-50",
    description: "Produto de Teste 50 BRF Bebidas",
    category: "Bebidas",
    brand: "BRF",
    unit: "Cx c/ 30",
    price: 25.11,
    stock: 159,
    imageUrl: "https://placehold.co/300x300?text=Produto+50",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 715.63
  },
  {
    id: "clubbi-mock-51",
    code: "CLB-MOCK-51",
    description: "Produto de Teste 51 Ambev Mercearia",
    category: "Mercearia",
    brand: "Ambev",
    unit: "Cx c/ 50",
    price: 4.92,
    stock: 109,
    imageUrl: "https://placehold.co/300x300?text=Produto+51",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 233.70
  },
  {
    id: "clubbi-mock-52",
    code: "CLB-MOCK-52",
    description: "Produto de Teste 52 Unilever Bebidas",
    category: "Bebidas",
    brand: "Unilever",
    unit: "Cx c/ 48",
    price: 8.17,
    stock: 134,
    imageUrl: "https://placehold.co/300x300?text=Produto+52",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 372.55
  },
  {
    id: "clubbi-mock-53",
    code: "CLB-MOCK-53",
    description: "Produto de Teste 53 BRF Bebidas",
    category: "Bebidas",
    brand: "BRF",
    unit: "Cx c/ 30",
    price: 48.15,
    stock: 195,
    imageUrl: "https://placehold.co/300x300?text=Produto+53",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1372.27
  },
  {
    id: "clubbi-mock-54",
    code: "CLB-MOCK-54",
    description: "Produto de Teste 54 Unilever Higiene",
    category: "Higiene",
    brand: "Unilever",
    unit: "Cx c/ 50",
    price: 6.01,
    stock: 171,
    imageUrl: "https://placehold.co/300x300?text=Produto+54",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 285.47
  },
  {
    id: "clubbi-mock-55",
    code: "CLB-MOCK-55",
    description: "Produto de Teste 55 Coca-Cola Higiene",
    category: "Higiene",
    brand: "Coca-Cola",
    unit: "Cx c/ 30",
    price: 30.57,
    stock: 91,
    imageUrl: "https://placehold.co/300x300?text=Produto+55",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 871.25
  },
  {
    id: "clubbi-mock-56",
    code: "CLB-MOCK-56",
    description: "Produto de Teste 56 Pepsico Biscoitos",
    category: "Biscoitos",
    brand: "Pepsico",
    unit: "Cx c/ 50",
    price: 28.97,
    stock: 53,
    imageUrl: "https://placehold.co/300x300?text=Produto+56",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1376.08
  },
  {
    id: "clubbi-mock-57",
    code: "CLB-MOCK-57",
    description: "Produto de Teste 57 Nestlé Frios",
    category: "Frios",
    brand: "Nestlé",
    unit: "Cx c/ 48",
    price: 6.85,
    stock: 241,
    imageUrl: "https://placehold.co/300x300?text=Produto+57",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 312.36
  },
  {
    id: "clubbi-mock-58",
    code: "CLB-MOCK-58",
    description: "Produto de Teste 58 Pepsico Higiene",
    category: "Higiene",
    brand: "Pepsico",
    unit: "Cx c/ 50",
    price: 50.20,
    stock: 183,
    imageUrl: "https://placehold.co/300x300?text=Produto+58",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2384.50
  },
  {
    id: "clubbi-mock-59",
    code: "CLB-MOCK-59",
    description: "Produto de Teste 59 Bauducco Frios",
    category: "Frios",
    brand: "Bauducco",
    unit: "Cx c/ 12",
    price: 33.94,
    stock: 135,
    imageUrl: "https://placehold.co/300x300?text=Produto+59",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 386.92
  },
  {
    id: "clubbi-mock-60",
    code: "CLB-MOCK-60",
    description: "Produto de Teste 60 Ambev Bebidas",
    category: "Bebidas",
    brand: "Ambev",
    unit: "Cx c/ 50",
    price: 6.03,
    stock: 165,
    imageUrl: "https://placehold.co/300x300?text=Produto+60",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 286.43
  },
  {
    id: "clubbi-mock-61",
    code: "CLB-MOCK-61",
    description: "Produto de Teste 61 Mondelez Bebidas",
    category: "Bebidas",
    brand: "Mondelez",
    unit: "Cx c/ 50",
    price: 42.68,
    stock: 138,
    imageUrl: "https://placehold.co/300x300?text=Produto+61",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2027.30
  },
  {
    id: "clubbi-mock-62",
    code: "CLB-MOCK-62",
    description: "Produto de Teste 62 Yoki Bebidas",
    category: "Bebidas",
    brand: "Yoki",
    unit: "Cx c/ 24",
    price: 3.77,
    stock: 71,
    imageUrl: "https://placehold.co/300x300?text=Produto+62",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 85.96
  },
  {
    id: "clubbi-mock-63",
    code: "CLB-MOCK-63",
    description: "Produto de Teste 63 Nestlé Frios",
    category: "Frios",
    brand: "Nestlé",
    unit: "Cx c/ 12",
    price: 35.97,
    stock: 221,
    imageUrl: "https://placehold.co/300x300?text=Produto+63",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 410.06
  },
  {
    id: "clubbi-mock-64",
    code: "CLB-MOCK-64",
    description: "Produto de Teste 64 Ambev Biscoitos",
    category: "Biscoitos",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 24.76,
    stock: 98,
    imageUrl: "https://placehold.co/300x300?text=Produto+64",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 564.53
  },
  {
    id: "clubbi-mock-65",
    code: "CLB-MOCK-65",
    description: "Produto de Teste 65 Ambev Frios",
    category: "Frios",
    brand: "Ambev",
    unit: "Cx c/ 50",
    price: 34.98,
    stock: 224,
    imageUrl: "https://placehold.co/300x300?text=Produto+65",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1661.55
  },
  {
    id: "clubbi-mock-66",
    code: "CLB-MOCK-66",
    description: "Produto de Teste 66 Ambev Frios",
    category: "Frios",
    brand: "Ambev",
    unit: "Cx c/ 50",
    price: 46.48,
    stock: 117,
    imageUrl: "https://placehold.co/300x300?text=Produto+66",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2207.80
  },
  {
    id: "clubbi-mock-67",
    code: "CLB-MOCK-67",
    description: "Produto de Teste 67 Nestlé Laticínios",
    category: "Laticínios",
    brand: "Nestlé",
    unit: "Cx c/ 12",
    price: 49.16,
    stock: 52,
    imageUrl: "https://placehold.co/300x300?text=Produto+67",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 560.42
  },
  {
    id: "clubbi-mock-68",
    code: "CLB-MOCK-68",
    description: "Produto de Teste 68 Danone Limpeza",
    category: "Limpeza",
    brand: "Danone",
    unit: "Cx c/ 24",
    price: 48.16,
    stock: 197,
    imageUrl: "https://placehold.co/300x300?text=Produto+68",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 1098.05
  },
  {
    id: "clubbi-mock-69",
    code: "CLB-MOCK-69",
    description: "Produto de Teste 69 Ambev Laticínios",
    category: "Laticínios",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 20.54,
    stock: 157,
    imageUrl: "https://placehold.co/300x300?text=Produto+69",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 468.31
  },
  {
    id: "clubbi-mock-70",
    code: "CLB-MOCK-70",
    description: "Produto de Teste 70 Coca-Cola Mercearia",
    category: "Mercearia",
    brand: "Coca-Cola",
    unit: "Cx c/ 30",
    price: 7.66,
    stock: 58,
    imageUrl: "https://placehold.co/300x300?text=Produto+70",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 218.31
  },
  {
    id: "clubbi-mock-71",
    code: "CLB-MOCK-71",
    description: "Produto de Teste 71 Mondelez Higiene",
    category: "Higiene",
    brand: "Mondelez",
    unit: "Cx c/ 12",
    price: 4.84,
    stock: 219,
    imageUrl: "https://placehold.co/300x300?text=Produto+71",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 55.18
  },
  {
    id: "clubbi-mock-72",
    code: "CLB-MOCK-72",
    description: "Produto de Teste 72 Danone Higiene",
    category: "Higiene",
    brand: "Danone",
    unit: "Cx c/ 30",
    price: 49.78,
    stock: 119,
    imageUrl: "https://placehold.co/300x300?text=Produto+72",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1418.73
  },
  {
    id: "clubbi-mock-73",
    code: "CLB-MOCK-73",
    description: "Produto de Teste 73 Ambev Bebidas",
    category: "Bebidas",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 51.98,
    stock: 61,
    imageUrl: "https://placehold.co/300x300?text=Produto+73",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 1185.14
  },
  {
    id: "clubbi-mock-74",
    code: "CLB-MOCK-74",
    description: "Produto de Teste 74 BRF Frios",
    category: "Frios",
    brand: "BRF",
    unit: "Cx c/ 50",
    price: 43.18,
    stock: 216,
    imageUrl: "https://placehold.co/300x300?text=Produto+74",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2051.05
  },
  {
    id: "clubbi-mock-75",
    code: "CLB-MOCK-75",
    description: "Produto de Teste 75 Ambev Biscoitos",
    category: "Biscoitos",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 34.01,
    stock: 141,
    imageUrl: "https://placehold.co/300x300?text=Produto+75",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 775.43
  },
  {
    id: "clubbi-mock-76",
    code: "CLB-MOCK-76",
    description: "Produto de Teste 76 Ambev Higiene",
    category: "Higiene",
    brand: "Ambev",
    unit: "Cx c/ 12",
    price: 12.46,
    stock: 247,
    imageUrl: "https://placehold.co/300x300?text=Produto+76",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 142.04
  },
  {
    id: "clubbi-mock-77",
    code: "CLB-MOCK-77",
    description: "Produto de Teste 77 Unilever Mercearia",
    category: "Mercearia",
    brand: "Unilever",
    unit: "Cx c/ 50",
    price: 50.23,
    stock: 168,
    imageUrl: "https://placehold.co/300x300?text=Produto+77",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2385.92
  },
  {
    id: "clubbi-mock-78",
    code: "CLB-MOCK-78",
    description: "Produto de Teste 78 Nestlé Higiene",
    category: "Higiene",
    brand: "Nestlé",
    unit: "Cx c/ 24",
    price: 7.75,
    stock: 192,
    imageUrl: "https://placehold.co/300x300?text=Produto+78",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 176.70
  },
  {
    id: "clubbi-mock-79",
    code: "CLB-MOCK-79",
    description: "Produto de Teste 79 Ambev Laticínios",
    category: "Laticínios",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 4.55,
    stock: 82,
    imageUrl: "https://placehold.co/300x300?text=Produto+79",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 103.74
  },
  {
    id: "clubbi-mock-80",
    code: "CLB-MOCK-80",
    description: "Produto de Teste 80 Ambev Frios",
    category: "Frios",
    brand: "Ambev",
    unit: "Cx c/ 50",
    price: 43.81,
    stock: 171,
    imageUrl: "https://placehold.co/300x300?text=Produto+80",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2080.97
  },
  {
    id: "clubbi-mock-81",
    code: "CLB-MOCK-81",
    description: "Produto de Teste 81 BRF Laticínios",
    category: "Laticínios",
    brand: "BRF",
    unit: "Cx c/ 50",
    price: 44.48,
    stock: 70,
    imageUrl: "https://placehold.co/300x300?text=Produto+81",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2112.80
  },
  {
    id: "clubbi-mock-82",
    code: "CLB-MOCK-82",
    description: "Produto de Teste 82 Unilever Mercearia",
    category: "Mercearia",
    brand: "Unilever",
    unit: "Cx c/ 48",
    price: 15.42,
    stock: 226,
    imageUrl: "https://placehold.co/300x300?text=Produto+82",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 703.15
  },
  {
    id: "clubbi-mock-83",
    code: "CLB-MOCK-83",
    description: "Produto de Teste 83 Ambev Laticínios",
    category: "Laticínios",
    brand: "Ambev",
    unit: "Cx c/ 24",
    price: 47.09,
    stock: 221,
    imageUrl: "https://placehold.co/300x300?text=Produto+83",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 1073.65
  },
  {
    id: "clubbi-mock-84",
    code: "CLB-MOCK-84",
    description: "Produto de Teste 84 Unilever Higiene",
    category: "Higiene",
    brand: "Unilever",
    unit: "Cx c/ 12",
    price: 44.88,
    stock: 146,
    imageUrl: "https://placehold.co/300x300?text=Produto+84",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 511.63
  },
  {
    id: "clubbi-mock-85",
    code: "CLB-MOCK-85",
    description: "Produto de Teste 85 Ambev Mercearia",
    category: "Mercearia",
    brand: "Ambev",
    unit: "Cx c/ 48",
    price: 24.95,
    stock: 129,
    imageUrl: "https://placehold.co/300x300?text=Produto+85",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 1137.72
  },
  {
    id: "clubbi-mock-86",
    code: "CLB-MOCK-86",
    description: "Produto de Teste 86 Mondelez Mercearia",
    category: "Mercearia",
    brand: "Mondelez",
    unit: "Cx c/ 30",
    price: 14.94,
    stock: 237,
    imageUrl: "https://placehold.co/300x300?text=Produto+86",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 425.79
  },
  {
    id: "clubbi-mock-87",
    code: "CLB-MOCK-87",
    description: "Produto de Teste 87 Danone Higiene",
    category: "Higiene",
    brand: "Danone",
    unit: "Cx c/ 50",
    price: 43.18,
    stock: 66,
    imageUrl: "https://placehold.co/300x300?text=Produto+87",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 2051.05
  },
  {
    id: "clubbi-mock-88",
    code: "CLB-MOCK-88",
    description: "Produto de Teste 88 Bauducco Biscoitos",
    category: "Biscoitos",
    brand: "Bauducco",
    unit: "Cx c/ 50",
    price: 22.00,
    stock: 212,
    imageUrl: "https://placehold.co/300x300?text=Produto+88",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1045.00
  },
  {
    id: "clubbi-mock-89",
    code: "CLB-MOCK-89",
    description: "Produto de Teste 89 Danone Biscoitos",
    category: "Biscoitos",
    brand: "Danone",
    unit: "Cx c/ 24",
    price: 21.92,
    stock: 74,
    imageUrl: "https://placehold.co/300x300?text=Produto+89",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 499.78
  },
  {
    id: "clubbi-mock-90",
    code: "CLB-MOCK-90",
    description: "Produto de Teste 90 Pepsico Limpeza",
    category: "Limpeza",
    brand: "Pepsico",
    unit: "Cx c/ 24",
    price: 44.33,
    stock: 86,
    imageUrl: "https://placehold.co/300x300?text=Produto+90",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 1010.72
  },
  {
    id: "clubbi-mock-91",
    code: "CLB-MOCK-91",
    description: "Produto de Teste 91 Danone Biscoitos",
    category: "Biscoitos",
    brand: "Danone",
    unit: "Cx c/ 12",
    price: 24.35,
    stock: 111,
    imageUrl: "https://placehold.co/300x300?text=Produto+91",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 277.59
  },
  {
    id: "clubbi-mock-92",
    code: "CLB-MOCK-92",
    description: "Produto de Teste 92 Danone Higiene",
    category: "Higiene",
    brand: "Danone",
    unit: "Cx c/ 30",
    price: 44.91,
    stock: 248,
    imageUrl: "https://placehold.co/300x300?text=Produto+92",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1279.93
  },
  {
    id: "clubbi-mock-93",
    code: "CLB-MOCK-93",
    description: "Produto de Teste 93 BRF Laticínios",
    category: "Laticínios",
    brand: "BRF",
    unit: "Cx c/ 24",
    price: 17.16,
    stock: 219,
    imageUrl: "https://placehold.co/300x300?text=Produto+93",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 391.25
  },
  {
    id: "clubbi-mock-94",
    code: "CLB-MOCK-94",
    description: "Produto de Teste 94 BRF Biscoitos",
    category: "Biscoitos",
    brand: "BRF",
    unit: "Cx c/ 30",
    price: 46.20,
    stock: 240,
    imageUrl: "https://placehold.co/300x300?text=Produto+94",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1316.70
  },
  {
    id: "clubbi-mock-95",
    code: "CLB-MOCK-95",
    description: "Produto de Teste 95 Coca-Cola Bebidas",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 50",
    price: 19.84,
    stock: 60,
    imageUrl: "https://placehold.co/300x300?text=Produto+95",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 942.40
  },
  {
    id: "clubbi-mock-96",
    code: "CLB-MOCK-96",
    description: "Produto de Teste 96 Pepsico Mercearia",
    category: "Mercearia",
    brand: "Pepsico",
    unit: "Cx c/ 12",
    price: 28.99,
    stock: 108,
    imageUrl: "https://placehold.co/300x300?text=Produto+96",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 330.49
  },
  {
    id: "clubbi-mock-97",
    code: "CLB-MOCK-97",
    description: "Produto de Teste 97 Ambev Biscoitos",
    category: "Biscoitos",
    brand: "Ambev",
    unit: "Cx c/ 50",
    price: 30.35,
    stock: 180,
    imageUrl: "https://placehold.co/300x300?text=Produto+97",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 1441.63
  },
  {
    id: "clubbi-mock-98",
    code: "CLB-MOCK-98",
    description: "Produto de Teste 98 Danone Limpeza",
    category: "Limpeza",
    brand: "Danone",
    unit: "Cx c/ 30",
    price: 51.20,
    stock: 118,
    imageUrl: "https://placehold.co/300x300?text=Produto+98",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 1459.20
  },
  {
    id: "clubbi-mock-99",
    code: "CLB-MOCK-99",
    description: "Produto de Teste 99 Yoki Higiene",
    category: "Higiene",
    brand: "Yoki",
    unit: "Cx c/ 48",
    price: 44.48,
    stock: 249,
    imageUrl: "https://placehold.co/300x300?text=Produto+99",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 2028.29
  },
  {
    id: "clubbi-mock-100",
    code: "CLB-MOCK-100",
    description: "Produto de Teste 100 Pepsico Frios",
    category: "Frios",
    brand: "Pepsico",
    unit: "Cx c/ 30",
    price: 27.10,
    stock: 157,
    imageUrl: "https://placehold.co/300x300?text=Produto+100",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 772.35
  }
];

const INITIAL_ORDERS = [
  {
    id: "ORD-5192",
    companyId: "coqueiro",
    clientCode: "CLI01",
    clientName: "Restaurante Tempero Bom",
    date: "2026-06-23T15:20:00Z",
    items: [
      { id: "coq-3", description: "Banana Prata de Hortifruti Clássica Kg", qty: 20, price: 6.90, unit: "Kg" },
      { id: "coq-1", description: "Biscoito Recheado Chocolate Piraquê Pacote 160g", qty: 5, price: 2.96, unit: "Un" }
    ],
    total: 152.80,
    notes: "Entregar bananas no ponto de amadurecimento médio.",
    status: "Recebido" // Recebido, Em Separação, Separado, Aguardando Retirada, Retirado, Cancelado
  }
];

export const initDb = () => {
  // Clear and force update se o novo "clubbi" tenant não estiver presente
  const existingCompanies = localStorage.getItem("facilitadora_companies");
  if (existingCompanies && !JSON.parse(existingCompanies)["clubbi"]) {
    localStorage.removeItem("facilitadora_companies");
    localStorage.removeItem("facilitadora_users");
    localStorage.removeItem("facilitadora_products");
  }
  // FORCE UPDATE for 100 products and new users
  localStorage.removeItem("facilitadora_products");
  localStorage.removeItem("facilitadora_users");

  if (!localStorage.getItem("facilitadora_companies")) {
    localStorage.setItem("facilitadora_companies", JSON.stringify(INITIAL_COMPANIES));
  }
  if (!localStorage.getItem("facilitadora_users")) {
    localStorage.setItem("facilitadora_users", JSON.stringify(INITIAL_USERS));
  }
  if (!localStorage.getItem("facilitadora_products")) {
    localStorage.setItem("facilitadora_products", JSON.stringify(INITIAL_PRODUCTS));
  }
  if (!localStorage.getItem("facilitadora_orders")) {
    localStorage.setItem("facilitadora_orders", JSON.stringify(INITIAL_ORDERS));
  }
};

// Companies Methods
export const getCompanies = () => {
  initDb();
  return JSON.parse(localStorage.getItem("facilitadora_companies"));
};

export const saveCompanies = (companies) => {
  localStorage.setItem("facilitadora_companies", JSON.stringify(companies));
};

// Users Methods
export const getUsers = () => {
  initDb();
  return JSON.parse(localStorage.getItem("facilitadora_users"));
};

export const saveUsers = (users) => {
  localStorage.setItem("facilitadora_users", JSON.stringify(users));
};

// Products Methods
export const getProducts = (companyId = null) => {
  initDb();
  const all = JSON.parse(localStorage.getItem("facilitadora_products"));
  if (!companyId) return all;
  return all.filter(p => p.companyId === companyId);
};

export const saveProducts = (products) => {
  localStorage.setItem("facilitadora_products", JSON.stringify(products));
};

// Orders Methods
export const getOrders = (companyId = null) => {
  initDb();
  const all = JSON.parse(localStorage.getItem("facilitadora_orders"));
  if (!companyId) return all;
  return all.filter(o => o.companyId === companyId);
};

export const saveOrders = (orders) => {
  localStorage.setItem("facilitadora_orders", JSON.stringify(orders));
};
