// Multi-tenant database simulation using localStorage for Mercado Online Facilitadora

const INITIAL_COMPANIES = {
  "coqueiro": {
    id: "coqueiro",
    name: "Casa Coqueiro",
    tradeName: "Casa Coqueiro Supermercados",
    logoUrl: "https://casacoqueiro.com.br/wp-content/uploads/2023/11/dddd-1.png",
    logoType: "image",
    primaryColor: "#059669", // Green
    secondaryColor: "#eab308", // Yellow
    accentColor: "#ef4444", // Red
    address: "Av. Copacabana, 500 - Copacabana, Rio de Janeiro - RJ",
    phone: "(21) 2233-4455",
    whatsapp: "(21) 98888-9999",
    hours: "08:00 às 20:00"
  },
  "horti-verde": {
    id: "horti-verde",
    name: "Hortifruti Verde Vale",
    tradeName: "Verde Vale Hortifruti & Cia",
    logoUrl: "",
    logoType: "text",
    logoText: "VerdeVale",
    primaryColor: "#16a34a",
    secondaryColor: "#166534",
    accentColor: "#ea580c",
    address: "Rua das Laranjeiras, 120 - Laranjeiras, Rio de Janeiro - RJ",
    phone: "(21) 3344-5566",
    whatsapp: "(21) 97777-8888",
    hours: "07:00 às 19:00"
  },
  "clubbi": {
    id: "clubbi",
    name: "Clubbi",
    tradeName: "Clubbi Distribuição B2B",
    logoUrl: "",
    logoType: "text",
    logoText: "Clubbi",
    primaryColor: "#3e34d3",
    secondaryColor: "#ece6fc",
    accentColor: "#38c172",
    address: "Av. das Américas, 500 - Barra da Tijuca, Rio de Janeiro - RJ",
    phone: "(21) 3003-4455",
    whatsapp: "(21) 96442-2488",
    hours: "08:00 às 18:00"
  }
};

const INITIAL_USERS = {
  // Global Admin Master
  "MASTER": {
    code: "MASTER",
    name: "Admin Master",
    role: "admin-master", // admin-master, store-admin, gestor, vendedor, cliente
    status: "Active",
    companyId: null
  },
  // Master Admin (WDPHP)
  "WDPHP": {
    code: "WDPHP",
    name: "Thiago (Admin Master)",
    role: "admin-master",
    status: "Active",
    companyId: null,
    phone: "21964422488"
  },
  // Client Test for Clubbi
  "CLI-CLUBBI": {
    code: "CLI-CLUBBI",
    name: "Mercadinho Bogados (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "clubbi",
    phone: "21964422488",
    address: "R. Cap. Edmundo Soares, 18 - K11 - Caonze, Nova Iguaçu - RJ, 26250-240"
  },
  "CLUBB": {
    code: "CLUBB",
    name: "Mercadinho Bogados (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "clubbi",
    phone: "21964422488",
    address: "R. Cap. Edmundo Soares, 18 - K11 - Caonze, Nova Iguaçu - RJ, 26250-240"
  },
  // Store Admin - Casa Coqueiro
  "ADM01": {
    code: "ADM01",
    name: "Roberto Coqueiro (Admin)",
    role: "store-admin",
    status: "Active",
    companyId: "coqueiro"
  },
  // Gestor - Casa Coqueiro
  "GES01": {
    code: "GES01",
    name: "Fernanda Lima (Gestor)",
    role: "gestor",
    status: "Active",
    companyId: "coqueiro",
    // Toggle-based permission states
    permissions: {
      financeiro: true,
      produtos: true,
      precos: true,
      clientes: true,
      funcionarios: true,
      relatorios: true,
      impressao: true,
      visualConfig: true,
      estoque: true,
      usuarios: true
    }
  },
  // Vendedor - Casa Coqueiro
  "VEN01": {
    code: "VEN01",
    name: "Carlos Silva (Vendedor)",
    role: "vendedor",
    status: "Active",
    companyId: "coqueiro",
    permissions: {
      financeiro: false,
      produtos: false,
      precos: false,
      clientes: true,
      funcionarios: false,
      relatorios: false,
      impressao: true,
      visualConfig: false,
      estoque: false,
      usuarios: false
    }
  },
  // Clients
  "CLI01": {
    code: "CLI01",
    name: "Restaurante Tempero Bom (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "coqueiro",
    phone: "(21) 98765-4321"
  },
  "CLI02": {
    code: "CLI02",
    name: "Padaria Copacabana (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "coqueiro",
    phone: "(21) 95555-4444"
  },
  "CLI03": {
    code: "CLI03",
    name: "Lanchonete Verde Vale (Cliente)",
    role: "cliente",
    status: "Active",
    companyId: "horti-verde",
    phone: "(21) 91111-2222"
  }
};

const INITIAL_PRODUCTS = [
  // Casa Coqueiro Catalog
  {
    id: "coq-1",
    code: "COQ-101",
    description: "Biscoito Recheado Chocolate Piraquê Pacote 160g",
    category: "Mercearia",
    brand: "Piraquê",
    unit: "Un",
    price: 2.96,
    stock: 150,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760357",
    companyId: "coqueiro"
  },
  {
    id: "coq-2",
    code: "COQ-102",
    description: "Isotônico Gatorade Pet Laranja 500ml",
    category: "Bebidas",
    brand: "Gatorade",
    unit: "Un",
    price: 4.85,
    stock: 80,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7892840808020",
    companyId: "coqueiro"
  },
  {
    id: "coq-3",
    code: "COQ-103",
    description: "Banana Prata de Hortifruti Clássica Kg",
    category: "Hortifruti",
    brand: "Produtor Rio",
    unit: "Kg",
    price: 6.90,
    stock: 200,
    imageUrl: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=200&auto=format&fit=crop&q=80",
    companyId: "coqueiro"
  },
  {
    id: "coq-4",
    code: "COQ-104",
    description: "Cereal Matinal Sucrilhos Kellogg's Original 110g",
    category: "Mercearia",
    brand: "Kellogg's",
    unit: "Un",
    price: 4.23,
    stock: 120,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896004007632",
    companyId: "coqueiro"
  },
  {
    id: "coq-5",
    code: "COQ-105",
    description: "Macarrão Instantâneo Galinha Nissin Miojo 85g",
    category: "Mercearia",
    brand: "Nissin",
    unit: "Un",
    price: 2.24,
    stock: 300,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7891079000229",
    companyId: "coqueiro"
  },
  {
    id: "coq-6",
    code: "COQ-106",
    description: "Leite de Coco Menina Garrafa 200ml",
    category: "Mercearia",
    brand: "Menina",
    unit: "Un",
    price: 3.10,
    stock: 90,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_120/f_png/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896028014494",
    companyId: "coqueiro"
  },

  // Hortifruti Verde Vale Catalog
  {
    id: "hv-1",
    code: "HVV-201",
    description: "Alface Crespa Hidropônica Unidade",
    category: "Hortifruti",
    brand: "Verde Vale",
    unit: "Un",
    price: 3.50,
    stock: 60,
    imageUrl: "https://images.unsplash.com/photo-1622484211148-716598e04141?w=200&auto=format&fit=crop&q=80",
    companyId: "horti-verde"
  },
  {
    id: "hv-2",
    code: "HVV-202",
    description: "Tomate Italiano maduro Selecionado Kg",
    category: "Hortifruti",
    brand: "Fazenda Orgânica",
    unit: "Kg",
    price: 8.90,
    stock: 140,
    imageUrl: "https://images.unsplash.com/photo-1595855759920-86582396756a?w=200&auto=format&fit=crop&q=80",
    companyId: "horti-verde"
  },
  {
    id: "hv-3",
    code: "HVV-203",
    description: "Suco de Uva Integral Aliança 1L",
    category: "Bebidas",
    brand: "Aliança",
    unit: "Un",
    price: 14.90,
    stock: 50,
    imageUrl: "",
    companyId: "horti-verde"
  },
  {
    id: "clubbi-9171",
    code: "CLB-100",
    description: "Biscoito Recheado Chocolate Piraquê Pacote 160g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760357",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 85.5
  },
  {
    id: "clubbi-3742",
    code: "CLB-101",
    description: "Biscoito Recheado Limão Piraquê Pacote 160g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760371",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 85.5
  },
  {
    id: "clubbi-9172",
    code: "CLB-102",
    description: "Biscoito Recheado Morango Piraquê Pacote 160g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024760364",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 85.5
  },
  {
    id: "clubbi-97694",
    code: "CLB-103",
    description: "Biscoito Maizena Piraquê Pacote 175g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 48",
    price: 2.96,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024761651",
    companyId: "clubbi",
    packageItems: 48,
    packagePrice: 136.8
  },
  {
    id: "clubbi-99429",
    code: "CLB-104",
    description: "Biscoito Leite Maltado Original Piraquê Pacote 132g",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 50",
    price: 2.8,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896024761439",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 134.5
  },
  {
    id: "clubbi-6144",
    code: "CLB-105",
    description: "Creme De Leite Leve Italac Tetra Pack 200g",
    category: "Derivados de Leite",
    brand: "Italac",
    unit: "Cx c/ 24",
    price: 2.65,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7898080640222",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 61.2
  },
  {
    id: "clubbi-3778",
    code: "CLB-106",
    description: "Leite De Coco Menina 200ml",
    category: "Preparo de Sobremesas",
    brand: "Menina",
    unit: "Cx c/ 24",
    price: 2.24,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7896028014494",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 51.6
  },
  {
    id: "clubbi-1398",
    code: "CLB-107",
    description: "Macarrão Instantâneo Galinha Caipira Nissin Miojo Lámen Pacote 85g",
    category: "Massas Secas",
    brand: "Nissin",
    unit: "Cx c/ 50",
    price: 2.24,
    stock: 100,
    imageUrl: "https://res.cloudinary.com/dti85ldyv/image/upload/c_scale,h_300/f_png,fl_progressive/b_white,c_limit,d_product-thumb_ybwmng.png/products/7891079000229",
    companyId: "clubbi",
    packageItems: 50,
    packagePrice: 107.5
  }
,
,
  {
    id: "clubbi-real-1",
    code: "CLB-REAL-1",
    description: "Suco Integral 1L Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 6",
    price: 12.49,
    stock: 189,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Suco%20Integral",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 71.19
  },
  {
    id: "clubbi-real-2",
    code: "CLB-REAL-2",
    description: "Extrato de Tomate 140g Fugini",
    category: "Mercearia",
    brand: "Fugini",
    unit: "Cx c/ 24",
    price: 2.84,
    stock: 243,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Extrato%20de",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 64.75
  },
  {
    id: "clubbi-real-3",
    code: "CLB-REAL-3",
    description: "Detergente Líquido Neutro 500ml Veja",
    category: "Limpeza",
    brand: "Veja",
    unit: "Cx c/ 24",
    price: 2.38,
    stock: 166,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Detergente%20L%C3%ADquido",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 54.26
  },
  {
    id: "clubbi-real-4",
    code: "CLB-REAL-4",
    description: "Detergente Líquido Neutro 500ml Veja",
    category: "Limpeza",
    brand: "Veja",
    unit: "Cx c/ 24",
    price: 2.38,
    stock: 247,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Detergente%20L%C3%ADquido",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 54.26
  },
  {
    id: "clubbi-real-5",
    code: "CLB-REAL-5",
    description: "Esponja Dupla Face 4un Veja",
    category: "Limpeza",
    brand: "Veja",
    unit: "Cx c/ 10",
    price: 7.15,
    stock: 231,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Esponja%20Dupla",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 67.92
  },
  {
    id: "clubbi-real-6",
    code: "CLB-REAL-6",
    description: "Arroz Tipo 1 5kg Soya",
    category: "Mercearia",
    brand: "Soya",
    unit: "Cx c/ 6",
    price: 27.31,
    stock: 175,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Arroz%20Tipo",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 155.67
  },
  {
    id: "clubbi-real-7",
    code: "CLB-REAL-7",
    description: "Cerveja Puro Malte 600ml Heineken",
    category: "Bebidas",
    brand: "Heineken",
    unit: "Cx c/ 24",
    price: 8.75,
    stock: 183,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Cerveja%20Puro",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 199.50
  },
  {
    id: "clubbi-real-8",
    code: "CLB-REAL-8",
    description: "Detergente Líquido Neutro 500ml Brilhante",
    category: "Limpeza",
    brand: "Brilhante",
    unit: "Cx c/ 24",
    price: 2.34,
    stock: 52,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Detergente%20L%C3%ADquido",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 53.35
  },
  {
    id: "clubbi-real-9",
    code: "CLB-REAL-9",
    description: "Condicionador 350ml Seda",
    category: "Higiene",
    brand: "Seda",
    unit: "Cx c/ 12",
    price: 19.16,
    stock: 115,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Condicionador%20350ml",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 218.42
  },
  {
    id: "clubbi-real-10",
    code: "CLB-REAL-10",
    description: "Leite UHT Integral 1L Elegê",
    category: "Laticínios",
    brand: "Elegê",
    unit: "Cx c/ 12",
    price: 5.04,
    stock: 162,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Leite%20UHT",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 57.46
  },
  {
    id: "clubbi-real-11",
    code: "CLB-REAL-11",
    description: "Sal Refinado 1kg Gallo",
    category: "Mercearia",
    brand: "Gallo",
    unit: "Cx c/ 30",
    price: 2.51,
    stock: 100,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Sal%20Refinado",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 71.53
  },
  {
    id: "clubbi-real-12",
    code: "CLB-REAL-12",
    description: "Refrigerante 2L Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 6",
    price: 9.85,
    stock: 194,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Refrigerante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 56.14
  },
  {
    id: "clubbi-real-13",
    code: "CLB-REAL-13",
    description: "Biscoito Água e Sal 200g Mabel",
    category: "Biscoitos",
    brand: "Mabel",
    unit: "Cx c/ 20",
    price: 4.07,
    stock: 148,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20%C3%81gua",
    companyId: "clubbi",
    packageItems: 20,
    packagePrice: 77.33
  },
  {
    id: "clubbi-real-14",
    code: "CLB-REAL-14",
    description: "Creme Dental Menta 90g Rexona",
    category: "Higiene",
    brand: "Rexona",
    unit: "Cx c/ 12",
    price: 4.51,
    stock: 146,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Creme%20Dental",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 51.41
  },
  {
    id: "clubbi-real-15",
    code: "CLB-REAL-15",
    description: "Queijo Parmesão Ralado 50g Nestlé",
    category: "Laticínios",
    brand: "Nestlé",
    unit: "Cx c/ 20",
    price: 5.63,
    stock: 197,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Queijo%20Parmes%C3%A3o",
    companyId: "clubbi",
    packageItems: 20,
    packagePrice: 106.97
  },
  {
    id: "clubbi-real-16",
    code: "CLB-REAL-16",
    description: "Energético 250ml Coca-Cola",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 6",
    price: 8.40,
    stock: 109,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Energ%C3%A9tico%20250ml",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 47.88
  },
  {
    id: "clubbi-real-17",
    code: "CLB-REAL-17",
    description: "Esponja Dupla Face 4un Omo",
    category: "Limpeza",
    brand: "Omo",
    unit: "Cx c/ 10",
    price: 6.78,
    stock: 169,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Esponja%20Dupla",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 64.41
  },
  {
    id: "clubbi-real-18",
    code: "CLB-REAL-18",
    description: "Farinha de Trigo 1kg Tio João",
    category: "Mercearia",
    brand: "Tio João",
    unit: "Cx c/ 10",
    price: 5.94,
    stock: 88,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Farinha%20de",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 56.43
  },
  {
    id: "clubbi-real-19",
    code: "CLB-REAL-19",
    description: "Esponja de Aço 8un Omo",
    category: "Limpeza",
    brand: "Omo",
    unit: "Cx c/ 14",
    price: 3.51,
    stock: 98,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Esponja%20de",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 46.68
  },
  {
    id: "clubbi-real-20",
    code: "CLB-REAL-20",
    description: "Shampoo Cabelos Normais 350ml Rexona",
    category: "Higiene",
    brand: "Rexona",
    unit: "Cx c/ 12",
    price: 18.40,
    stock: 233,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Shampoo%20Cabelos",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 209.76
  },
  {
    id: "clubbi-real-21",
    code: "CLB-REAL-21",
    description: "Água Mineral Sem Gás 500ml Coca-Cola",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 12",
    price: 1.52,
    stock: 224,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=%C3%81gua%20Mineral",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 17.33
  },
  {
    id: "clubbi-real-22",
    code: "CLB-REAL-22",
    description: "Café Torrado e Moído 500g Gallo",
    category: "Mercearia",
    brand: "Gallo",
    unit: "Cx c/ 10",
    price: 17.17,
    stock: 102,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Caf%C3%A9%20Torrado",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 163.12
  },
  {
    id: "clubbi-real-23",
    code: "CLB-REAL-23",
    description: "Bolo Sabor Laranja 250g Marilan",
    category: "Biscoitos",
    brand: "Marilan",
    unit: "Cx c/ 14",
    price: 8.15,
    stock: 133,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 108.39
  },
  {
    id: "clubbi-real-24",
    code: "CLB-REAL-24",
    description: "Bolo Sabor Laranja 250g Piraquê",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 14",
    price: 7.66,
    stock: 184,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 101.88
  },
  {
    id: "clubbi-real-25",
    code: "CLB-REAL-25",
    description: "Biscoito de Polvilho 100g Mabel",
    category: "Biscoitos",
    brand: "Mabel",
    unit: "Cx c/ 24",
    price: 3.73,
    stock: 205,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20de",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 85.04
  },
  {
    id: "clubbi-real-26",
    code: "CLB-REAL-26",
    description: "Desodorante Aerosol 150ml Rexona",
    category: "Higiene",
    brand: "Rexona",
    unit: "Cx c/ 12",
    price: 16.55,
    stock: 167,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Desodorante%20Aerosol",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 188.67
  },
  {
    id: "clubbi-real-27",
    code: "CLB-REAL-27",
    description: "Café Torrado e Moído 500g Camil",
    category: "Mercearia",
    brand: "Camil",
    unit: "Cx c/ 10",
    price: 17.49,
    stock: 58,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Caf%C3%A9%20Torrado",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 166.15
  },
  {
    id: "clubbi-real-28",
    code: "CLB-REAL-28",
    description: "Wafer Chocolate 120g Marilan",
    category: "Biscoitos",
    brand: "Marilan",
    unit: "Cx c/ 30",
    price: 3.04,
    stock: 234,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Wafer%20Chocolate",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 86.64
  },
  {
    id: "clubbi-real-29",
    code: "CLB-REAL-29",
    description: "Água Sanitária 2L Bom Bril",
    category: "Limpeza",
    brand: "Bom Bril",
    unit: "Cx c/ 6",
    price: 5.41,
    stock: 229,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=%C3%81gua%20Sanit%C3%A1ria",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 30.84
  },
  {
    id: "clubbi-real-30",
    code: "CLB-REAL-30",
    description: "Extrato de Tomate 140g Knorr",
    category: "Mercearia",
    brand: "Knorr",
    unit: "Cx c/ 24",
    price: 2.72,
    stock: 154,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Extrato%20de",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 62.02
  },
  {
    id: "clubbi-real-31",
    code: "CLB-REAL-31",
    description: "Creme de Queijo Minas 200g Piracanjuba",
    category: "Laticínios",
    brand: "Piracanjuba",
    unit: "Cx c/ 12",
    price: 7.70,
    stock: 212,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Creme%20de",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 87.78
  },
  {
    id: "clubbi-real-32",
    code: "CLB-REAL-32",
    description: "Biscoito Recheado Chocolate 140g Bauducco",
    category: "Biscoitos",
    brand: "Bauducco",
    unit: "Cx c/ 30",
    price: 3.66,
    stock: 211,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20Recheado",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 104.31
  },
  {
    id: "clubbi-real-33",
    code: "CLB-REAL-33",
    description: "Amaciante 2L Veja",
    category: "Limpeza",
    brand: "Veja",
    unit: "Cx c/ 6",
    price: 11.07,
    stock: 227,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Amaciante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 63.10
  },
  {
    id: "clubbi-real-34",
    code: "CLB-REAL-34",
    description: "Azeite Extra Virgem 500ml Fugini",
    category: "Mercearia",
    brand: "Fugini",
    unit: "Cx c/ 6",
    price: 32.53,
    stock: 174,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Azeite%20Extra",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 185.42
  },
  {
    id: "clubbi-real-35",
    code: "CLB-REAL-35",
    description: "Fio Dental 50m Oral-B",
    category: "Higiene",
    brand: "Oral-B",
    unit: "Cx c/ 12",
    price: 8.65,
    stock: 225,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Fio%20Dental",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 98.61
  },
  {
    id: "clubbi-real-36",
    code: "CLB-REAL-36",
    description: "Shampoo Cabelos Normais 350ml Dove",
    category: "Higiene",
    brand: "Dove",
    unit: "Cx c/ 12",
    price: 18.51,
    stock: 72,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Shampoo%20Cabelos",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 211.01
  },
  {
    id: "clubbi-real-37",
    code: "CLB-REAL-37",
    description: "Desodorante Aerosol 150ml Oral-B",
    category: "Higiene",
    brand: "Oral-B",
    unit: "Cx c/ 12",
    price: 15.60,
    stock: 123,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Desodorante%20Aerosol",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 177.84
  },
  {
    id: "clubbi-real-38",
    code: "CLB-REAL-38",
    description: "Requeijão Tradicional 200g Nestlé",
    category: "Laticínios",
    brand: "Nestlé",
    unit: "Cx c/ 24",
    price: 8.81,
    stock: 112,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Requeij%C3%A3o%20Tradicional",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 200.87
  },
  {
    id: "clubbi-real-39",
    code: "CLB-REAL-39",
    description: "Óleo de Soja 900ml Soya",
    category: "Mercearia",
    brand: "Soya",
    unit: "Cx c/ 20",
    price: 6.05,
    stock: 70,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=%C3%93leo%20de",
    companyId: "clubbi",
    packageItems: 20,
    packagePrice: 114.95
  },
  {
    id: "clubbi-real-40",
    code: "CLB-REAL-40",
    description: "Refrigerante 2L Heineken",
    category: "Bebidas",
    brand: "Heineken",
    unit: "Cx c/ 6",
    price: 9.59,
    stock: 193,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Refrigerante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 54.66
  },
  {
    id: "clubbi-real-41",
    code: "CLB-REAL-41",
    description: "Papel Higiênico Folha Dupla 4un Pantene",
    category: "Higiene",
    brand: "Pantene",
    unit: "Cx c/ 16",
    price: 7.72,
    stock: 75,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Papel%20Higi%C3%AAnico",
    companyId: "clubbi",
    packageItems: 16,
    packagePrice: 117.34
  },
  {
    id: "clubbi-real-42",
    code: "CLB-REAL-42",
    description: "Água Tônica Lata 350ml Heineken",
    category: "Bebidas",
    brand: "Heineken",
    unit: "Cx c/ 6",
    price: 3.98,
    stock: 119,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=%C3%81gua%20T%C3%B4nica",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 22.69
  },
  {
    id: "clubbi-real-43",
    code: "CLB-REAL-43",
    description: "Cookies Tradicional 100g Nestlé",
    category: "Biscoitos",
    brand: "Nestlé",
    unit: "Cx c/ 24",
    price: 6.02,
    stock: 74,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Cookies%20Tradicional",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 137.26
  },
  {
    id: "clubbi-real-44",
    code: "CLB-REAL-44",
    description: "Bolo Sabor Laranja 250g Piraquê",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 14",
    price: 7.78,
    stock: 152,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 103.47
  },
  {
    id: "clubbi-real-45",
    code: "CLB-REAL-45",
    description: "Amaciante 2L Ypê",
    category: "Limpeza",
    brand: "Ypê",
    unit: "Cx c/ 6",
    price: 11.21,
    stock: 218,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Amaciante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 63.90
  },
  {
    id: "clubbi-real-46",
    code: "CLB-REAL-46",
    description: "Água Tônica Lata 350ml Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 6",
    price: 3.76,
    stock: 111,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=%C3%81gua%20T%C3%B4nica",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 21.43
  },
  {
    id: "clubbi-real-47",
    code: "CLB-REAL-47",
    description: "Queijo Parmesão Ralado 50g Itambé",
    category: "Laticínios",
    brand: "Itambé",
    unit: "Cx c/ 20",
    price: 5.53,
    stock: 75,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Queijo%20Parmes%C3%A3o",
    companyId: "clubbi",
    packageItems: 20,
    packagePrice: 105.07
  },
  {
    id: "clubbi-real-48",
    code: "CLB-REAL-48",
    description: "Papel Higiênico Folha Dupla 4un Colgate",
    category: "Higiene",
    brand: "Colgate",
    unit: "Cx c/ 16",
    price: 7.34,
    stock: 150,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Papel%20Higi%C3%AAnico",
    companyId: "clubbi",
    packageItems: 16,
    packagePrice: 111.57
  },
  {
    id: "clubbi-real-49",
    code: "CLB-REAL-49",
    description: "Queijo Parmesão Ralado 50g Elegê",
    category: "Laticínios",
    brand: "Elegê",
    unit: "Cx c/ 20",
    price: 5.71,
    stock: 170,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Queijo%20Parmes%C3%A3o",
    companyId: "clubbi",
    packageItems: 20,
    packagePrice: 108.49
  },
  {
    id: "clubbi-real-50",
    code: "CLB-REAL-50",
    description: "Leite Condensado 395g Fugini",
    category: "Mercearia",
    brand: "Fugini",
    unit: "Cx c/ 24",
    price: 6.54,
    stock: 54,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Leite%20Condensado",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 149.11
  },
  {
    id: "clubbi-real-51",
    code: "CLB-REAL-51",
    description: "Feijão Carioca 1kg Gallo",
    category: "Mercearia",
    brand: "Gallo",
    unit: "Cx c/ 10",
    price: 7.57,
    stock: 189,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Feij%C3%A3o%20Carioca",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 71.92
  },
  {
    id: "clubbi-real-52",
    code: "CLB-REAL-52",
    description: "Bebida Láctea Achocolatada 200ml Elegê",
    category: "Laticínios",
    brand: "Elegê",
    unit: "Cx c/ 27",
    price: 2.11,
    stock: 76,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bebida%20L%C3%A1ctea",
    companyId: "clubbi",
    packageItems: 27,
    packagePrice: 54.12
  },
  {
    id: "clubbi-real-53",
    code: "CLB-REAL-53",
    description: "Sabão em Pó 1kg Omo",
    category: "Limpeza",
    brand: "Omo",
    unit: "Cx c/ 12",
    price: 15.17,
    stock: 155,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Sab%C3%A3o%20em",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 172.94
  },
  {
    id: "clubbi-real-54",
    code: "CLB-REAL-54",
    description: "Absorvente com Abas 8un Seda",
    category: "Higiene",
    brand: "Seda",
    unit: "Cx c/ 16",
    price: 5.39,
    stock: 51,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Absorvente%20com",
    companyId: "clubbi",
    packageItems: 16,
    packagePrice: 81.93
  },
  {
    id: "clubbi-real-55",
    code: "CLB-REAL-55",
    description: "Biscoito Amanteigado 300g Piraquê",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 12",
    price: 8.10,
    stock: 140,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20Amanteigado",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 92.34
  },
  {
    id: "clubbi-real-56",
    code: "CLB-REAL-56",
    description: "Refrigerante 2L Coca-Cola",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 6",
    price: 9.57,
    stock: 235,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Refrigerante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 54.55
  },
  {
    id: "clubbi-real-57",
    code: "CLB-REAL-57",
    description: "Água Mineral Sem Gás 500ml Coca-Cola",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 12",
    price: 1.55,
    stock: 226,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=%C3%81gua%20Mineral",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 17.67
  },
  {
    id: "clubbi-real-58",
    code: "CLB-REAL-58",
    description: "Água Tônica Lata 350ml Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 6",
    price: 3.96,
    stock: 164,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=%C3%81gua%20T%C3%B4nica",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 22.57
  },
  {
    id: "clubbi-real-59",
    code: "CLB-REAL-59",
    description: "Bebida Láctea Achocolatada 200ml Itambé",
    category: "Laticínios",
    brand: "Itambé",
    unit: "Cx c/ 27",
    price: 2.14,
    stock: 179,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bebida%20L%C3%A1ctea",
    companyId: "clubbi",
    packageItems: 27,
    packagePrice: 54.89
  },
  {
    id: "clubbi-real-60",
    code: "CLB-REAL-60",
    description: "Farinha de Trigo 1kg Gallo",
    category: "Mercearia",
    brand: "Gallo",
    unit: "Cx c/ 10",
    price: 5.77,
    stock: 181,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Farinha%20de",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 54.81
  },
  {
    id: "clubbi-real-61",
    code: "CLB-REAL-61",
    description: "Saco para Lixo 50L 30un Ypê",
    category: "Limpeza",
    brand: "Ypê",
    unit: "Cx c/ 10",
    price: 12.75,
    stock: 239,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Saco%20para",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 121.13
  },
  {
    id: "clubbi-real-62",
    code: "CLB-REAL-62",
    description: "Enxaguante Bucal 500ml Colgate",
    category: "Higiene",
    brand: "Colgate",
    unit: "Cx c/ 6",
    price: 23.67,
    stock: 140,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Enxaguante%20Bucal",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 134.92
  },
  {
    id: "clubbi-real-63",
    code: "CLB-REAL-63",
    description: "Açúcar Refinado 1kg Yoki",
    category: "Mercearia",
    brand: "Yoki",
    unit: "Cx c/ 10",
    price: 4.04,
    stock: 247,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=A%C3%A7%C3%BAcar%20Refinado",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 38.38
  },
  {
    id: "clubbi-real-64",
    code: "CLB-REAL-64",
    description: "Refrigerante 2L Coca-Cola",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 6",
    price: 9.07,
    stock: 141,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Refrigerante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 51.70
  },
  {
    id: "clubbi-real-65",
    code: "CLB-REAL-65",
    description: "Bolo Sabor Laranja 250g Oreo",
    category: "Biscoitos",
    brand: "Oreo",
    unit: "Cx c/ 14",
    price: 7.85,
    stock: 177,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 104.40
  },
  {
    id: "clubbi-real-66",
    code: "CLB-REAL-66",
    description: "Creme Dental Menta 90g Colgate",
    category: "Higiene",
    brand: "Colgate",
    unit: "Cx c/ 12",
    price: 4.33,
    stock: 216,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Creme%20Dental",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 49.36
  },
  {
    id: "clubbi-real-67",
    code: "CLB-REAL-67",
    description: "Leite UHT Desnatado 1L Elegê",
    category: "Laticínios",
    brand: "Elegê",
    unit: "Cx c/ 12",
    price: 5.10,
    stock: 240,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Leite%20UHT",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 58.14
  },
  {
    id: "clubbi-real-68",
    code: "CLB-REAL-68",
    description: "Água Tônica Lata 350ml Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 6",
    price: 3.95,
    stock: 176,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=%C3%81gua%20T%C3%B4nica",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 22.52
  },
  {
    id: "clubbi-real-69",
    code: "CLB-REAL-69",
    description: "Refrigerante 2L Heineken",
    category: "Bebidas",
    brand: "Heineken",
    unit: "Cx c/ 6",
    price: 9.29,
    stock: 106,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Refrigerante%202L",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 52.95
  },
  {
    id: "clubbi-real-70",
    code: "CLB-REAL-70",
    description: "Manteiga Extra com Sal 200g Itambé",
    category: "Laticínios",
    brand: "Itambé",
    unit: "Cx c/ 12",
    price: 13.39,
    stock: 107,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Manteiga%20Extra",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 152.65
  },
  {
    id: "clubbi-real-71",
    code: "CLB-REAL-71",
    description: "Extrato de Tomate 140g Gallo",
    category: "Mercearia",
    brand: "Gallo",
    unit: "Cx c/ 24",
    price: 2.91,
    stock: 53,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=Extrato%20de",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 66.35
  },
  {
    id: "clubbi-real-72",
    code: "CLB-REAL-72",
    description: "Detergente Líquido Neutro 500ml Bom Bril",
    category: "Limpeza",
    brand: "Bom Bril",
    unit: "Cx c/ 24",
    price: 2.26,
    stock: 204,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Detergente%20L%C3%ADquido",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 51.53
  },
  {
    id: "clubbi-real-73",
    code: "CLB-REAL-73",
    description: "Cerveja Puro Malte 600ml Heineken",
    category: "Bebidas",
    brand: "Heineken",
    unit: "Cx c/ 24",
    price: 8.59,
    stock: 247,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Cerveja%20Puro",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 195.85
  },
  {
    id: "clubbi-real-74",
    code: "CLB-REAL-74",
    description: "Wafer Chocolate 120g Marilan",
    category: "Biscoitos",
    brand: "Marilan",
    unit: "Cx c/ 30",
    price: 3.06,
    stock: 185,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Wafer%20Chocolate",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 87.21
  },
  {
    id: "clubbi-real-75",
    code: "CLB-REAL-75",
    description: "Haste Flexível 75un Rexona",
    category: "Higiene",
    brand: "Rexona",
    unit: "Cx c/ 24",
    price: 3.97,
    stock: 230,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Haste%20Flex%C3%ADvel",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 90.52
  },
  {
    id: "clubbi-real-76",
    code: "CLB-REAL-76",
    description: "Detergente Líquido Neutro 500ml Ypê",
    category: "Limpeza",
    brand: "Ypê",
    unit: "Cx c/ 24",
    price: 2.27,
    stock: 235,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Detergente%20L%C3%ADquido",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 51.76
  },
  {
    id: "clubbi-real-77",
    code: "CLB-REAL-77",
    description: "Energético 250ml Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 6",
    price: 8.71,
    stock: 192,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Energ%C3%A9tico%20250ml",
    companyId: "clubbi",
    packageItems: 6,
    packagePrice: 49.65
  },
  {
    id: "clubbi-real-78",
    code: "CLB-REAL-78",
    description: "Biscoito Recheado Chocolate 140g Piraquê",
    category: "Biscoitos",
    brand: "Piraquê",
    unit: "Cx c/ 30",
    price: 3.67,
    stock: 202,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20Recheado",
    companyId: "clubbi",
    packageItems: 30,
    packagePrice: 104.59
  },
  {
    id: "clubbi-real-79",
    code: "CLB-REAL-79",
    description: "Cerveja Pilsen Lata 350ml Del Valle",
    category: "Bebidas",
    brand: "Del Valle",
    unit: "Cx c/ 12",
    price: 3.08,
    stock: 116,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Cerveja%20Pilsen",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 35.11
  },
  {
    id: "clubbi-real-80",
    code: "CLB-REAL-80",
    description: "Manteiga Extra com Sal 200g Elegê",
    category: "Laticínios",
    brand: "Elegê",
    unit: "Cx c/ 12",
    price: 13.22,
    stock: 225,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Manteiga%20Extra",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 150.71
  },
  {
    id: "clubbi-real-81",
    code: "CLB-REAL-81",
    description: "Biscoito Amanteigado 300g Oreo",
    category: "Biscoitos",
    brand: "Oreo",
    unit: "Cx c/ 12",
    price: 8.13,
    stock: 219,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20Amanteigado",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 92.68
  },
  {
    id: "clubbi-real-82",
    code: "CLB-REAL-82",
    description: "Creme de Queijo Minas 200g Nestlé",
    category: "Laticínios",
    brand: "Nestlé",
    unit: "Cx c/ 12",
    price: 7.87,
    stock: 55,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Creme%20de",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 89.72
  },
  {
    id: "clubbi-real-83",
    code: "CLB-REAL-83",
    description: "Desodorante Aerosol 150ml Oral-B",
    category: "Higiene",
    brand: "Oral-B",
    unit: "Cx c/ 12",
    price: 15.51,
    stock: 124,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Desodorante%20Aerosol",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 176.81
  },
  {
    id: "clubbi-real-84",
    code: "CLB-REAL-84",
    description: "Sabão em Barra 5un Omo",
    category: "Limpeza",
    brand: "Omo",
    unit: "Cx c/ 10",
    price: 10.26,
    stock: 136,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Sab%C3%A3o%20em",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 97.47
  },
  {
    id: "clubbi-real-85",
    code: "CLB-REAL-85",
    description: "Sabão em Pó 1kg Omo",
    category: "Limpeza",
    brand: "Omo",
    unit: "Cx c/ 12",
    price: 15.25,
    stock: 151,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Sab%C3%A3o%20em",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 173.85
  },
  {
    id: "clubbi-real-86",
    code: "CLB-REAL-86",
    description: "Bolo Sabor Laranja 250g Nestlé",
    category: "Biscoitos",
    brand: "Nestlé",
    unit: "Cx c/ 14",
    price: 7.69,
    stock: 142,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 102.28
  },
  {
    id: "clubbi-real-87",
    code: "CLB-REAL-87",
    description: "Cerveja Pilsen Lata 350ml Coca-Cola",
    category: "Bebidas",
    brand: "Coca-Cola",
    unit: "Cx c/ 12",
    price: 3.35,
    stock: 78,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Cerveja%20Pilsen",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 38.19
  },
  {
    id: "clubbi-real-88",
    code: "CLB-REAL-88",
    description: "Bolo Sabor Laranja 250g Bauducco",
    category: "Biscoitos",
    brand: "Bauducco",
    unit: "Cx c/ 14",
    price: 7.97,
    stock: 110,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 106.00
  },
  {
    id: "clubbi-real-89",
    code: "CLB-REAL-89",
    description: "Manteiga Extra com Sal 200g Batavo",
    category: "Laticínios",
    brand: "Batavo",
    unit: "Cx c/ 12",
    price: 13.39,
    stock: 55,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Manteiga%20Extra",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 152.65
  },
  {
    id: "clubbi-real-90",
    code: "CLB-REAL-90",
    description: "Cerveja Pilsen Lata 350ml Pepsi",
    category: "Bebidas",
    brand: "Pepsi",
    unit: "Cx c/ 12",
    price: 3.09,
    stock: 102,
    imageUrl: "https://placehold.co/300x300/0284c7/ffffff?text=Cerveja%20Pilsen",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 35.23
  },
  {
    id: "clubbi-real-91",
    code: "CLB-REAL-91",
    description: "Saco para Lixo 50L 30un Veja",
    category: "Limpeza",
    brand: "Veja",
    unit: "Cx c/ 10",
    price: 13.34,
    stock: 178,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Saco%20para",
    companyId: "clubbi",
    packageItems: 10,
    packagePrice: 126.73
  },
  {
    id: "clubbi-real-92",
    code: "CLB-REAL-92",
    description: "Papel Higiênico Folha Dupla 4un Colgate",
    category: "Higiene",
    brand: "Colgate",
    unit: "Cx c/ 16",
    price: 7.20,
    stock: 206,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Papel%20Higi%C3%AAnico",
    companyId: "clubbi",
    packageItems: 16,
    packagePrice: 109.44
  },
  {
    id: "clubbi-real-93",
    code: "CLB-REAL-93",
    description: "Manteiga Extra com Sal 200g Nestlé",
    category: "Laticínios",
    brand: "Nestlé",
    unit: "Cx c/ 12",
    price: 12.43,
    stock: 149,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Manteiga%20Extra",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 141.70
  },
  {
    id: "clubbi-real-94",
    code: "CLB-REAL-94",
    description: "Leite UHT Desnatado 1L Itambé",
    category: "Laticínios",
    brand: "Itambé",
    unit: "Cx c/ 12",
    price: 5.11,
    stock: 240,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Leite%20UHT",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 58.25
  },
  {
    id: "clubbi-real-95",
    code: "CLB-REAL-95",
    description: "Biscoito de Polvilho 100g Bauducco",
    category: "Biscoitos",
    brand: "Bauducco",
    unit: "Cx c/ 24",
    price: 3.75,
    stock: 177,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20de",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 85.50
  },
  {
    id: "clubbi-real-96",
    code: "CLB-REAL-96",
    description: "Óleo de Soja 900ml Gallo",
    category: "Mercearia",
    brand: "Gallo",
    unit: "Cx c/ 20",
    price: 5.98,
    stock: 234,
    imageUrl: "https://placehold.co/300x300/ea580c/ffffff?text=%C3%93leo%20de",
    companyId: "clubbi",
    packageItems: 20,
    packagePrice: 113.62
  },
  {
    id: "clubbi-real-97",
    code: "CLB-REAL-97",
    description: "Bolo Sabor Laranja 250g Oreo",
    category: "Biscoitos",
    brand: "Oreo",
    unit: "Cx c/ 14",
    price: 7.87,
    stock: 112,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Bolo%20Sabor",
    companyId: "clubbi",
    packageItems: 14,
    packagePrice: 104.67
  },
  {
    id: "clubbi-real-98",
    code: "CLB-REAL-98",
    description: "Leite UHT Integral 1L Batavo",
    category: "Laticínios",
    brand: "Batavo",
    unit: "Cx c/ 12",
    price: 4.96,
    stock: 177,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Leite%20UHT",
    companyId: "clubbi",
    packageItems: 12,
    packagePrice: 56.54
  },
  {
    id: "clubbi-real-99",
    code: "CLB-REAL-99",
    description: "Biscoito de Polvilho 100g Mabel",
    category: "Biscoitos",
    brand: "Mabel",
    unit: "Cx c/ 24",
    price: 4.05,
    stock: 211,
    imageUrl: "https://placehold.co/300x300/475569/ffffff?text=Biscoito%20de",
    companyId: "clubbi",
    packageItems: 24,
    packagePrice: 92.34
  },
  {
    id: "clubbi-real-100",
    code: "CLB-REAL-100",
    description: "Papel Higiênico Folha Dupla 4un Oral-B",
    category: "Higiene",
    brand: "Oral-B",
    unit: "Cx c/ 16",
    price: 7.56,
    stock: 98,
    imageUrl: "https://placehold.co/300x300/0891b2/ffffff?text=Papel%20Higi%C3%AAnico",
    companyId: "clubbi",
    packageItems: 16,
    packagePrice: 114.91
  }
];

const INITIAL_ORDERS = [
  {
    id: "ORD-5192",
    companyId: "coqueiro",
    clientCode: "CLI01",
    clientName: "Restaurante Tempero Bom",
    date: "2026-06-23T15:20:00Z",
    items: [
      { id: "coq-3", description: "Banana Prata de Hortifruti Clássica Kg", qty: 20, price: 6.90, unit: "Kg" },
      { id: "coq-1", description: "Biscoito Recheado Chocolate Piraquê Pacote 160g", qty: 5, price: 2.96, unit: "Un" }
    ],
    total: 152.80,
    notes: "Entregar bananas no ponto de amadurecimento médio.",
    status: "Recebido" // Recebido, Em Separação, Separado, Aguardando Retirada, Retirado, Cancelado
  }
];

export const initDb = () => {
  // Clear and force update se o novo "clubbi" tenant não estiver presente
  const existingCompanies = localStorage.getItem("facilitadora_companies");
  if (existingCompanies && !JSON.parse(existingCompanies)["clubbi"]) {
    localStorage.removeItem("facilitadora_companies");
    localStorage.removeItem("facilitadora_users");
    localStorage.removeItem("facilitadora_products");
  }
  // FORCE UPDATE for 100 products and new users
  localStorage.removeItem("facilitadora_products");
  localStorage.removeItem("facilitadora_users");

  if (!localStorage.getItem("facilitadora_companies")) {
    localStorage.setItem("facilitadora_companies", JSON.stringify(INITIAL_COMPANIES));
  }
  if (!localStorage.getItem("facilitadora_users")) {
    localStorage.setItem("facilitadora_users", JSON.stringify(INITIAL_USERS));
  }
  if (!localStorage.getItem("facilitadora_products")) {
    localStorage.setItem("facilitadora_products", JSON.stringify(INITIAL_PRODUCTS));
  }
  if (!localStorage.getItem("facilitadora_orders")) {
    localStorage.setItem("facilitadora_orders", JSON.stringify(INITIAL_ORDERS));
  }
};

// Companies Methods
export const getCompanies = () => {
  initDb();
  return JSON.parse(localStorage.getItem("facilitadora_companies"));
};

export const saveCompanies = (companies) => {
  localStorage.setItem("facilitadora_companies", JSON.stringify(companies));
};

// Users Methods
export const getUsers = () => {
  initDb();
  return JSON.parse(localStorage.getItem("facilitadora_users"));
};

export const saveUsers = (users) => {
  localStorage.setItem("facilitadora_users", JSON.stringify(users));
};

// Products Methods
export const getProducts = (companyId = null) => {
  initDb();
  const all = JSON.parse(localStorage.getItem("facilitadora_products"));
  if (!companyId) return all;
  return all.filter(p => p.companyId === companyId);
};

export const saveProducts = (products) => {
  localStorage.setItem("facilitadora_products", JSON.stringify(products));
};

// Orders Methods
export const getOrders = (companyId = null) => {
  initDb();
  const all = JSON.parse(localStorage.getItem("facilitadora_orders"));
  if (!companyId) return all;
  return all.filter(o => o.companyId === companyId);
};

export const saveOrders = (orders) => {
  localStorage.setItem("facilitadora_orders", JSON.stringify(orders));
};
